pod_namespace: default
prowjob_namespace: jx
postsubmits:
  gitcpu-io/jx-demo: #org/repo的名字,这里需要替换
    - agent: tekton-pipeline
      branches:
        - master  #确定你的仓库也是main的分支，如果是master请修改
      context: tekton
      name: tekton-pipeline
      pipeline_run_spec: #这里的pipeline运行spec需要是上面创建的名字
        pipelineRef:
          name: jx-demo-pipeline
        workspaces:
          - name: source-workspace
            subPath: source
            persistentVolumeClaim:
              claimName: buildpacks-source-pvc
          - name: cache-workspace
            subPath: cache
            persistentVolumeClaim:
              claimName: buildpacks-source-pvc
        params:
          - name: argocd-url
            value: "argocd-server.argocd" #argocd-server service address
          - name: argocd-secret
            value: "argocd-oauth" #must be create secret for argocd username and password
          - name: repo-url
            value: "https://github.com/gitcpu-io/jx-demo" #code repo
          - name: repo-revision
            value: ""
          - name: repo-image
            value: "rubinus/jx-demo"  #image url for docker registry
          - name: app-name
            value: "jx-demo"  #argocd application name must be create before on the argocd
          - name: app-revision
            value: ""

        serviceAccountName: buildpacks-service-account

presubmits:
  gitcpu-io/jx-demo: #需要替换成你的组织名/仓库名
    - name: run-unit-test
      agent: tekton-pipeline
      context: tekton
      always_run: true
      rerun_command: /test this
      trigger: (?m)^/test( all| this),?(s+|$)
      pipeline_run_spec: #这里的pipeline运行spec需要是上面创建的名字
        pipelineRef:
          name: jx-demo-pre-pipeline
        workspaces:
          - name: source-workspace
            subPath: source
            persistentVolumeClaim:
              claimName: buildpacks-source-pvc
        params:
          - name: repo-url
            value: "https://github.com/gitcpu-io/jx-demo" #code repo
          - name: repo-revision
            value: ""
tide:
  queries:
    - repos:
        - gitcpu-io/jx-demo  #org/repo的名字,这里需要替换
      labels:
        - lgtm
        - approved

